### ISSUE TITLE
FYI: you can replace choose with emacs 

### ISSUE THREAD

**Issue by QiangF** [ginqi7/global-interactive-emacs#1]
https://github.com/QiangF/erofi

**Comment by ginqi7** [comment]
I try to test =erofi=. Unfortunately, it didn't work out successfully. In my MacOs, it just can run as a terminal not GUI. Maybe my config is not compatible.

I took a look through it's code. it's core idea is let emacsclient create new frame just having minibuffer only. so you could use minibuffer as a interactive interface. Am I right?

This idea maybe a good choies. using emacs minibuffer could aviod some potential problems. I will try this solution, when I have time.

Now using =choose= is just ok, my attention will focus improve the functions of =global-interactive-emacs=

Thanks for your advice, I will try it later.

If you have any other ides, I look forward your suggestion.

**Comment by QiangF** [comment]
Yes, it uses minibuffer as a interactive interface.
Rofi doesn't support input method, so if your language is not English, you have problem. I haven't used choose.
